// Code generated by MockGen. DO NOT EDIT.
// Source: mapper.go

// Package mapping is a generated GoMock package.
package mapping

import (
	gomock "github.com/golang/mock/gomock"
	autoeq "github.com/indiependente/autoEqMac/autoeq"
	eqmac "github.com/indiependente/autoEqMac/eqmac"
	reflect "reflect"
)

// MockMapper is a mock of Mapper interface
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
}

// MockMapperMockRecorder is the mock recorder for MockMapper
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// MapFixedBand mocks base method
func (m *MockMapper) MapFixedBand(arg0 autoeq.FixedBandEQs, arg1 autoeq.EQMetadata) (eqmac.EQPreset, error) {
	ret := m.ctrl.Call(m, "MapFixedBand", arg0, arg1)
	ret0, _ := ret[0].(eqmac.EQPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapFixedBand indicates an expected call of MapFixedBand
func (mr *MockMapperMockRecorder) MapFixedBand(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapFixedBand", reflect.TypeOf((*MockMapper)(nil).MapFixedBand), arg0, arg1)
}
