// Code generated by MockGen. DO NOT EDIT.
// Source: mapper.go

// Package mapping is a generated GoMock package.
package mapping

import (
	gomock "github.com/golang/mock/gomock"
	autoeq "github.com/indiependente/autoEqMac/autoeq"
	eqmac "github.com/indiependente/autoEqMac/eqmac"
	reflect "reflect"
)

// MockUUIDGenerator is a mock of UUIDGenerator interface
type MockUUIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDGeneratorMockRecorder
}

// MockUUIDGeneratorMockRecorder is the mock recorder for MockUUIDGenerator
type MockUUIDGeneratorMockRecorder struct {
	mock *MockUUIDGenerator
}

// NewMockUUIDGenerator creates a new mock instance
func NewMockUUIDGenerator(ctrl *gomock.Controller) *MockUUIDGenerator {
	mock := &MockUUIDGenerator{ctrl: ctrl}
	mock.recorder = &MockUUIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUUIDGenerator) EXPECT() *MockUUIDGeneratorMockRecorder {
	return m.recorder
}

// UUID mocks base method
func (m *MockUUIDGenerator) UUID() string {
	ret := m.ctrl.Call(m, "UUID")
	ret0, _ := ret[0].(string)
	return ret0
}

// UUID indicates an expected call of UUID
func (mr *MockUUIDGeneratorMockRecorder) UUID() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UUID", reflect.TypeOf((*MockUUIDGenerator)(nil).UUID))
}

// MockMapper is a mock of Mapper interface
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
}

// MockMapperMockRecorder is the mock recorder for MockMapper
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// MapFixedBand mocks base method
func (m *MockMapper) MapFixedBand(arg0 autoeq.FixedBandEQ, arg1 autoeq.EQMetadata) (eqmac.EQPreset, error) {
	ret := m.ctrl.Call(m, "MapFixedBand", arg0, arg1)
	ret0, _ := ret[0].(eqmac.EQPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapFixedBand indicates an expected call of MapFixedBand
func (mr *MockMapperMockRecorder) MapFixedBand(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapFixedBand", reflect.TypeOf((*MockMapper)(nil).MapFixedBand), arg0, arg1)
}
